
#ifndef _INTEL_GIGABIT_LAN_POLICY_PROTOCOL_GUID_H_
#define _INTEL_GIGABIT_LAN_POLICY_PROTOCOL_GUID_H_

#define INTEL_GIGABIT_LAN_POLICY_PROTOCOL_GUID {0x2BD77D17, 0x3771, 0x4974, { 0x86, 0x44, 0xF9, 0x9C, 0xF5, 0xB2, 0x66, 0xA7 }}

EFI_STATUS
EFIAPI
InstalGigabitLanPolicyProtocol (
  VOID		
  );

#endif // _INTEL_GIGABIT_LAN_POLICY_PROTOCOL_GUID_H_
